---
- name: Get Fixhub from repository
  git: repo="https://github.com/Fixhub/Fixhub.git" dest={{fixhub_directory}} version={{fixhub_version}} force=yes update=yes
  register: version_modified

- name: Install fixhub dependencies (Composer)
  composer: command="install" no_dev=yes optimize_autoloader=yes working_dir={{fixhub_directory}}
  when: version_modified.changed

- name: Install fixhub dependencies (NPM)
  npm: path={{fixhub_directory}} production=yes
  when: version_modified.changed

- name: Set writable permissions for public directories
  file: path={{item}} mode=0777 recurse=yes state=directory
  with_items:
  - "{{fixhub_directory}}/storage"
  - "{{fixhub_directory}}/public/upload"

- name: Check if fixhub configuration file exists
  stat: path={{fixhub_directory}}/.env
  register: configuration_exists

- name: Install fixhub configuration file
  template: src=env.fixhub.j2 dest={{fixhub_directory}}/.env

- name: Run scripts to complete fixhub installation
  shell: "{{item}}"
  args:
    chdir: "{{fixhub_directory}}"
  with_items:
  - "php artisan clear-compiled"
  - "php artisan cache:clear"
  - "php artisan route:clear"
  - "php artisan config:clear"
  - "php artisan view:clear"
  - "php artisan optimize --force"
  - "php artisan key:generate"
  - "php artisan jwt:generate"
  - "php artisan config:cache"
  - "php artisan route:cache"
  - "php artisan migrate --force"
  - "npm install --production"

- name: Update fixhub
  shell: 'printf \"\yes\" | php artisan app:update'
  args:
    chdir: "{{fixhub_directory}}"
  when: (configuration_exists.stat.exists == True and version_modified.changed == True)

- name: Create Fixhub cron job
  cron: name="Fixhub schedule" job="sudo php {{fixhub_directory}}/artisan schedule:run 1>> /dev/null 2>&1"

- name: Create supervisor configuration file
  template: src=fixhub.conf.j2 dest=/etc/supervisor/conf.d/fixhub.conf
  notify: start supervisor
